### PR TITLE
Form connection

### PR DESCRIPTION
**Pull request by dc4472**
This is a draft pull request of everything for newtask backend. I want to test everything on newtask first as once it works there, edit task will be easy. I am having trouble with console testing for my part on the backend, but I am figuring it out.

### CODE REVIEW

**Comment by dc4472** [comment]
I just finished the back-end code. This will be the last of express code before I implement unit tests in a separate branch. NewTask works now. I will also try edittask in another branch,

**Review by Khalifa-AlFalasi — CHANGES_REQUESTED** [review]
Seems to be working just fine. Only comment is to delete the extra file "NewTask.js" in the back-end which is almost empty.

**Comment by dc4472** [comment]
I just deleted the newtask.js in back end without any code.

**Review by Khalifa-AlFalasi — APPROVED** [review]
seems good

**Pull request merged**
